create table MBR_INFO(
	MBR_ID TEXT PRIMARY KEY,
	TALK TEXT,
	COIN TEXT,
	PURCHASE TEXT,
	DEPOSIT TEXT,
	SALE TEXT,
	WITHDRAW TEXT,
	RESERVE TEXT,
	TOTAL_PUR TEXT,
	TOTAL_SAL TEXT,
	REVENUE TEXT,
	RATING TEXT,
	WALLET TEXT
	);


-- 답변
-- insert into MBR_INFO(MBR_ID, TITLE, MBR_INFO) values(1, '여행_짐', '1박2일 짧은 여행을 떠날 때에 나는...');