# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'formDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5.QtWidgets import QDialog, QGridLayout, QWidget, QLabel, QPushButton \
                            , QLineEdit, QApplication, QMessageBox

from PyQt5.QtCore import QRect, QMetaObject, QSize, Qt
from PyQt5.QtGui import QFont

import static.staticValues as staticValues

class FormDialog(QDialog):

    def __init__(self):
        super().__init__()
        self.setupUi()

    def setupUi(self):
        #메인 화면 색상py
        # self.setStyleSheet("color: black;"
        #                 "border-width: 1px;")
        
        self.resize(550, 680)
        self.setMinimumSize(QSize(550, 680))
        self.setMaximumSize(QSize(550, 680))
        self.label_2 = QLabel(self)
        self.label_2.setGeometry(QRect(10, 16, 101, 21))
        self.label_2.setStyleSheet("border: 0px;")
        font = QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.button_submit = QPushButton(self)
        self.button_submit.setGeometry(QRect(300, 630, 93, 28))
        self.layoutWidget = QWidget(self)
        self.layoutWidget.setGeometry(QRect(10, 47, 511, 561))
        self.layoutWidget.setStyleSheet("border: 0px;")

        self.gridLayout = QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.label_11 = QLabel(self.layoutWidget)
        self.label_11.setStyleSheet("border: 0px;")

        self.label_point1 = QLabel(self)
        self.label_point1.setText("*")
        self.label_point1.setGeometry(QRect(10,50,15,15))
        self.label_point1.setStyleSheet("border: 0px; color: red;")

        self.label_point2 = QLabel(self)
        self.label_point2.setText("*")
        self.label_point2.setGeometry(QRect(10,90,15,15))
        self.label_point2.setStyleSheet("border: 0px; color: red;")

        self.gridLayout.addWidget(self.label_11, 9, 0, 1, 1)

        self.label_6 = QLabel(self.layoutWidget)
        self.label_6.setStyleSheet("border: 0px;")

        self.gridLayout.addWidget(self.label_6, 4, 0, 1, 1)
        self.label_8 = QLabel(self.layoutWidget)
        self.label_8.setStyleSheet("border: 0px;")
        
        self.gridLayout.addWidget(self.label_8, 6, 0, 1, 1)
        self.label_9 = QLabel(self.layoutWidget)
        self.label_9.setStyleSheet("border: 0px;")

        self.gridLayout.addWidget(self.label_9, 7, 0, 1, 1)
        self.label_12 = QLabel(self.layoutWidget)
        self.label_12.setStyleSheet("border: 0px;")

        self.gridLayout.addWidget(self.label_12, 10, 0, 1, 1)
        self.label_7 = QLabel(self.layoutWidget)
        self.label_7.setStyleSheet("border: 0px;")

        self.gridLayout.addWidget(self.label_7, 5, 0, 1, 1)

        self.edit_pur = QLineEdit(self.layoutWidget)
        self.edit_pur.setStyleSheet(staticValues.solidStyleSheet)
        self.gridLayout.addWidget(self.edit_pur, 3, 1, 1, 2)

        self.label_13 = QLabel(self.layoutWidget)
        self.label_13.setStyleSheet("border: 0px;")

        self.gridLayout.addWidget(self.label_13, 11, 0, 1, 1)

        self.edit_dep = QLineEdit(self.layoutWidget)
        self.edit_dep.setStyleSheet(staticValues.solidStyleSheet)
        self.gridLayout.addWidget(self.edit_dep, 4, 1, 1, 2)

        self.edit_sal = QLineEdit(self.layoutWidget)
        self.edit_sal.setStyleSheet(staticValues.solidStyleSheet)
        self.gridLayout.addWidget(self.edit_sal, 5, 1, 1, 2)

        self.label_4 = QLabel(self.layoutWidget)
        self.label_4.setStyleSheet("border: 0px;")
        
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)

        self.edit_coin = QLineEdit(self.layoutWidget)
        self.edit_coin.setStyleSheet(staticValues.solidStyleSheet)
        self.gridLayout.addWidget(self.edit_coin, 2, 1, 1, 2)

        self.label_5 = QLabel(self.layoutWidget)
        self.label_5.setStyleSheet("border: 0px;")

        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.label_3 = QLabel(self.layoutWidget)
        self.label_3.setStyleSheet("border: 0px;")

        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)

        self.edit_talk = QLineEdit(self.layoutWidget)
        self.edit_talk.setStyleSheet(staticValues.solidStyleSheet)
        self.gridLayout.addWidget(self.edit_talk, 1, 1, 1, 2)

        self.button_doubleCheck = QPushButton(self.layoutWidget)
        self.gridLayout.addWidget(self.button_doubleCheck, 0, 2, 1, 1)
        self.label = QLabel(self.layoutWidget)
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)

        self.edit_id = QLineEdit(self.layoutWidget)
        self.edit_id.setStyleSheet(staticValues.solidStyleSheet)

        self.gridLayout.addWidget(self.edit_id, 0, 1, 1, 1)
        self.label_10 = QLabel(self.layoutWidget)
        self.label_10.setStyleSheet("border: 0px;")

        self.gridLayout.addWidget(self.label_10, 8, 0, 1, 1)
        self.label_14 = QLabel(self.layoutWidget)
        self.label_14.setStyleSheet("border: 0px;")

        self.gridLayout.addWidget(self.label_14, 12, 0, 1, 1)

        self.edit_withd = QLineEdit(self.layoutWidget)
        self.edit_withd.setStyleSheet(staticValues.solidStyleSheet)

        self.gridLayout.addWidget(self.edit_withd, 6, 1, 1, 2)
        self.edit_reserve = QLineEdit(self.layoutWidget)
        self.edit_reserve.setStyleSheet(staticValues.solidStyleSheet)
        
        self.gridLayout.addWidget(self.edit_reserve, 7, 1, 1, 2)
        self.edit_totpur = QLineEdit(self.layoutWidget)
        self.edit_totpur.setStyleSheet(staticValues.solidStyleSheet)

        self.gridLayout.addWidget(self.edit_totpur, 8, 1, 1, 2)
        self.edit_totsal = QLineEdit(self.layoutWidget)
        self.edit_totsal.setStyleSheet(staticValues.solidStyleSheet)

        self.gridLayout.addWidget(self.edit_totsal, 9, 1, 1, 2)
        self.edit_revenue = QLineEdit(self.layoutWidget)
        self.edit_revenue.setStyleSheet(staticValues.solidStyleSheet)

        self.gridLayout.addWidget(self.edit_revenue, 10, 1, 1, 2)
        self.edit_rating = QLineEdit(self.layoutWidget)
        self.edit_rating.setStyleSheet(staticValues.solidStyleSheet)

        self.gridLayout.addWidget(self.edit_rating, 11, 1, 1, 2)
        self.edit_wallet = QLineEdit(self.layoutWidget)
        self.edit_wallet.setStyleSheet(staticValues.solidStyleSheet)

        self.gridLayout.addWidget(self.edit_wallet, 12, 1, 1, 2)
        self.button_cancle = QPushButton(self)
        self.button_cancle.setGeometry(QRect(130, 630, 93, 28))

        #버튼 스타일 변경
        self.button_cancle.setStyleSheet(staticValues.grayButtonStyleSheet)
        self.button_cancle.setFont(staticValues.buttonFont)
        self.button_cancle.clicked.connect(self.close)
        
        self.button_submit.setStyleSheet(staticValues.blueButtonStyleSheet)
        self.button_submit.setFont(staticValues.buttonFont)

        self.button_doubleCheck.setStyleSheet(staticValues.blueButtonStyleSheet)
        self.button_doubleCheck.setFont(staticValues.buttonFont)

        self.retranslateUi()
        QMetaObject.connectSlotsByName(self)

        flags = Qt.WindowFlags(Qt.FramelessWindowHint | Qt.Window)
        self.setWindowFlags(flags)

    
    def retranslateUi(self):
        self.setWindowTitle("회원 추가")
        self.label_2.setText("회원 추가")
        self.button_submit.setText("추가")
        self.label_11.setText("총판매금액")
        self.label_6.setText("입금")
        self.label_8.setText("출금")
        self.label_9.setText("보유잔량")
        self.label_12.setText("수익")
        self.label_7.setText("판매")
        self.label_13.setText("평단가")
        self.label_4.setText("코인명")
        self.label_5.setText("구매")
        self.label_3.setText("단톡방")
        self.button_doubleCheck.setText("중복확인")
        self.label.setText("회원ID")
        self.label_10.setText("총구매금액")
        self.label_14.setText("지갑주소")
        self.button_cancle.setText("취소")

    

if __name__ == "__main__":
    import sys
    app = QApplication(sys.argv)
    ui = FormDialog()
    ui.show()
    sys.exit(app.exec_())
